// <auto-generated />
namespace WbMyFather.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRow_PageEdit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRow_PageEdit));
        
        string IMigrationMetadata.Id
        {
            get { return "201701111905007_AddRow_PageEdit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
